### PR TITLE
Added stipulation of no direct linking to auto downloads

### PR DESCRIPTION
**Pull request by carstorm**
Also put whats suggested to link to (projects overview page)

### CODE REVIEW

**Comment by JamiesWhiteShirt** [comment]
I don't think this needs enforcement. It should be in the announcer's interest to avoid this issue and present it in a reasonable way. It seems so far we have only _one instance_ of this, and I believe it is a mistake.

**Review by jriwanek — CHANGES_REQUESTED** [review]
automaticlly -> automatically
recommend -> recommended

**Comment by JamiesWhiteShirt** [comment]
`recommended`*

**Comment by carstorm** [comment]
@JamiesWhiteShirt The stipulation of realizing accidents happen means we don't need to enforce it every time. I agree that it doesn't happen often but this will let us be future proof. It comes across as suspicious (to people to to the scene) or otherwise annoying.

@jriwanek Fixed spelling errors and hopefully pushed correctly.

**Review by jriwanek — APPROVED** [review]

**Review by Darkhax — CHANGES_REQUESTED** [review]
If the purpose of this change is to discourage linking direct downloads, and not to create a new rule, I think it would be better to make this change less rule like. If we want to take the new rule route this would be better as an actual new rule and not part of the channel description. 

A less rule-like way of wording it would be something like the following quote. Doing it in this way would allow the infraction to be covered by mal-con or other. 

>Used by the community to share announcements for their own projects. We request that you link to the project overview page rather than a direct download. Responses and discussion about announcements should be done in a separate channel, however adding reaction emoji is fine.

**Review by Dizzy611 — APPROVED** [review]

**Comment by jriwanek** [comment]
@carstorm Status update on requested changes please?

**Comment by antoinegag** [comment]
Is this still relevant?

**Comment by antoinegag** [comment]
Following up in #9

**Pull request closed without merging**
